### ISSUE TITLE
[PACE-3] Add multi-tenant support

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#15]
Currently, PACE is a single-tenant application. No authentication and no scoped resources for a specific user / org / dept / etc.

<sub>[PACE-3](https://linear.app/strmprivacy/issue/PACE-3/add-multi-tenant-support)</sub>

**Comment by bvdeenen** [comment]
This is a very large issue where we would have to very seriously design an interaction with an existing authz platform. Probably great to do this as a plugin.

**Comment by trietsch** [comment]
Agreed! I've created this as a placeholder, as we'd need quite a bit of insight into different needs for multi-tenancy before we build anything here.
