### ISSUE TITLE
[PACE-4] Release pipeline should update various resources on the main branch

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#17]
After doing a release (i.e. a pipeline triggering after doing a GitHub release), some resources should be updated on the main branch:
- Buf generated dependency version
- ...

<sub>[PACE-4](https://linear.app/strmprivacy/issue/PACE-4/release-pipeline-should-update-various-resources-on-the-main-branch)</sub>

**Comment by trietsch** [comment]
@ivan-p92 I doubt that we need to do this. The buf generated dependency version equals the version upon merge of the PR, which is the version that correctly compiles.
The "tagged" release of the generated dependency version is not different (also, in the actual Maven artifact, the version does not include the tag itself, so there is no benefit there either).
The actual version that we use when creating the actual release artifact (the container image), is only created during the CI that runs on the tag, and if we were to publish that to the source branch from which the tag was created, we would need to commit back to that branch. The flow would then look like: `PR -> alpha -> tag X -> alpha`. Not worth the effort IMO.

**Comment by ivan-p92** [comment]
Indeed, I think you're right 👌
