### ISSUE TITLE
[PACE-5] Collibra databases don't show full name

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#20]
```
pace list databases --catalog COLLIBRA-testdrive
databases:

catalog:
id: COLLIBRA-testdrive
type: COLLIBRA
id: 8665f375-e08a-4810-add6-7af490f748ad
type: Snowflake

catalog:
id: COLLIBRA-testdrive
type: COLLIBRA
id: 99379294-6e87-4e26-9f09-21c6bf86d415
type: CData JDBC Driver for Google BigQuery 2021

catalog:
id: COLLIBRA-testdrive
type: COLLIBRA
id: b6e043a7-88f1-42ee-8e81-0fdc1c96f471
type: Snowflake
```

The field `displayName` is not filled in, and it should contain something useful

<sub>From [SyncLinear.com](https://synclinear.com) | [PACE-5](https://linear.app/strmprivacy/issue/PACE-5/collibra-databases-dont-show-full-name)</sub>

**Comment by bvdeenen** [comment]
pace list databases --catalog COLLIBRA-testdrive
databases:
- catalog:
    id: COLLIBRA-testdrive
    type: COLLIBRA
  id: 8665f375-e08a-4810-add6-7af490f748ad
  type: Snowflake
- catalog:
    id: COLLIBRA-testdrive
    type: COLLIBRA
  id: 99379294-6e87-4e26-9f09-21c6bf86d415
  type: CData JDBC Driver for Google BigQuery 2021
- catalog:
    id: COLLIBRA-testdrive
    type: COLLIBRA
  id: b6e043a7-88f1-42ee-8e81-0fdc1c96f471
  type: Snowflake

The field `displayName` is not filled in, and it should contain something useful
