### ISSUE TITLE
[PACE-12] Add optional extra Postgres grant that allows any other user with view access

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#25]
The view that is created by PACE, isn't automatically accessible by any user that has access to the postgres cluster (this may apply to other processing platforms as well). Add an optional flag (api change) that allows for configuring arbitrary access to the view.

<sub>[PACE-12](https://linear.app/strmprivacy/issue/PACE-12/add-optional-extra-postgres-grant-that-allows-any-other-user-with-view)</sub>

**Comment by ivan-p92** [comment]
This applies to all platforms. The question is to what extent this is the responsibility of PACE. I can imagine users prefer to do these grants from their provisioning layer. Read/select grants are often granted on parent schemas and can also be inherited from DB-level or similar.

**Comment by trietsch** [comment]
Agreed with your comments. I've ran into this while creating the standalone example, and therefore I created this issue to make sure we discuss it.
