### ISSUE TITLE
[PACE-1] Make PACE more lenient regarding casing

### ISSUE THREAD

**Issue by ivan-p92** [getstrm/pace#29]
In the SQL world, casing requirements of table names and fields are typically quite lenient. In PACE however, some interactions may fail if such casing mismatches. This can be confusing.

<sub>[PACE-1](https://linear.app/strmprivacy/issue/PACE-1/make-pace-more-lenient-regarding-casing)</sub>

**Comment by bvdeenen** [comment]
I think this is especially relevant with the principal groups. We currently check for strict equality, but this should become a loose match based on what would work at sql level.
