### ISSUE TITLE
[PACE-2] Consider using template methods for transforms

### ISSUE THREAD

**Issue by ivan-p92** [getstrm/pace#30]
In other words, let specific sql converters implement (or override) transforms defined in the abstract sql generator. This way, we could support a hashing function for Postgres and or BigQuery.

Note: the built-in BigQuery hash function is limited to string or bytearray input, and bytearray output. This can be casted to string again, but this means that if you'd have a principal without hash and one with hash, that they would have a different data type. So this could be trickier than expected.

For Postgres, it looks like there are [different hashing functions](https://stackoverflow.com/a/69650940) depending on the type. Although this is perhaps also the case for Snowflake and Databricks, maybe we just didn't run into it with our sample policies.

I say "consider" in the title of this ticket as you could argue that users could use the SQL statement transform to do this instead (although the principal data type issue could happen there too).

<sub>[PACE-2](https://linear.app/strmprivacy/issue/PACE-2/consider-using-template-methods-for-transforms)</sub>

**Comment by bvdeenen** [comment]
I think that has already been implemented now with the Transformer subclasses.

**Comment by ivan-p92** [comment]
Yes indeed, I meant to close it but forgot.
