### ISSUE TITLE
[PACE-19] Add support for data retention

### ISSUE THREAD

**Issue by astronomous** [getstrm/pace#32]
When implementing a data policy, I would like to specify a retention period, after which data should be omitted from the created view. 

Details:
- In the rulesets, add support for retention
- take a specified retention period (in days), indicated by a tag
- In building the dynamic view, check if a row is inside or outside of the retention period
- Design choice: checks should be conducted from the creation (not update) timestamp of each row
- If outside of the retention period, filter out the row.
- Question: would it be possible to delete the source data altogether instead of filtering out from a view only?

<sub>[PACE-19](https://linear.app/strmprivacy/issue/PACE-19/draft-add-support-for-data-retention)</sub>

**Comment by bvdeenen** [comment]
Doing this we also need to make sure we can correctly parse row timestamps. There are many timestamp formats in use in SQL tables, sometimes they're just stored as strings.

**Comment by ivan-p92** [comment]
This was not an action of mine in Linear, probably something with the GitHub sync. I've seen it with other tickets too.
