### ISSUE TITLE
[PACE-40] Add full application configuration reference to docs

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#54]
A full application configuration is very useful as a reference. We might even have something like a JSON schema to document the different properties and their purposes.

<sub>[PACE-40](https://linear.app/strmprivacy/issue/PACE-40/add-full-application-configuration-reference-to-docs)</sub>

**Comment by trietsch** [comment]
@bvdeenen the processing platform configuration pages link to GitHub instead of a dedicated page in the docs. I'm reopening this as that shouldn't be the case IMO. If this was meant to work like this, could you explain why?

**Comment by bvdeenen** [comment]
> @bvdeenen the processing platform configuration pages link to GitHub instead of a dedicated page in the docs. I'm reopening this as that shouldn't be the case IMO. If this was meant to work like this, could you explain why?

Shouldn't be, I don't know how this happened. I'll check

**Comment by bvdeenen** [comment]
Ok, this was only the postgres configuration, that I forgot from SUMMARY.md
Other links are fine.
