### ISSUE TITLE
[PACE-41] Offer default transformations

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#55]
Options:
- Examples
- Global transforms (tag based, or library based?)
- other?

<sub>[PACE-42](https://linear.app/strmprivacy/issue/PACE-42/offer-default-transformations)</sub>

**Comment by trietsch** [comment]
Candidate for [PACE-22](https://linear.app/strmprivacy/issue/PACE-22/setup-plugin-system).

**Comment by bvdeenen** [comment]
isn't this one done?
