### ISSUE TITLE
[PACE-44] Setup processing platform integration tests

### ISSUE THREAD

**Issue by trietsch** [getstrm/pace#56]
**Problem description**
In order to test transforms and platform specific implementations, we should set up some form of integration tests.

**Proposed solution**
TBD

<sub>[PACE-44](https://linear.app/strmprivacy/issue/PACE-44/setup-processing-platform-integration-tests)</sub>

**Comment by astronomous** [comment]
As suggested, because we need to test the data integrity, I think approaching this trough eg Soda or Great Expectations (or any other good data quality tool) is worthwhile to explore.

**Comment by astronomous** [comment]
whoopsie
